sudo: required
services:
  - docker

before_install:
  - docker build -t awaghadsangita/docker_react_frontendApp -f Dockerfile.dev .

script:
  - docker run awaghadsangita/docker_react_frontendApp npm run test -- --coverage