sudo: required
services:
  - docker

before_install:
  - docker build --tag myimage -f Dockerfile.dev .

script:
  - docker run myimage npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: elasticbeanstalk-ap-south-1-739837302708
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"